
name: Manual maven steps for ci
on:
    pull_request:
      branches: 
        - main
    workflow_dispatch:

permissions: 
     contents: read
     checks: write
     pull-requests: write 
     actions : read
     security-events : write
    
jobs:
  call-reusable:
    uses: nharshitha29/MULTI--CLOUD/.github/workflows/reusable-mvn.yaml@v1
    with:
      java-version: '21'
      agent: 'ubuntu-latest'